### ISSUE TITLE
Clone to pubnation ogranisation

### ISSUE THREAD

**Issue by MateuszJeziorski** [nanek/pn-logging#14]
Hi @ahaurw01 

I wonder if we shouldn't make clone of this repo and push to pubnation organisation in github. What do you think about that?

**Comment by ahaurw01** [comment]
Totally up to you, @MateuszJeziorski. We previously open sourced this repo for simplicity.

**Comment by MateuszJeziorski** [comment]
I see. Just in case I did fork to pubnation org
https://github.com/pubnation/pn-logging
